[project]
name = "costumes"
version = "0.1.0"
description = "Turn two images into animated one"
readme = "README.md"
authors = [{ name = "kuzminklk", email = "kuzminkdk@gmail.com" }]
requires-python = ">=3.11"
dependencies = ["pillow>=12.3.0"]

[project.scripts]
costumes = "costumes:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
