[project]
name = "watch"
version = "0.1.0"
description = "Parse YouTube link from embed HTML and transform"
readme = "README.md"
authors = [{ name = "kuzminkdk", email = "kuzminkdk@gmail.com" }]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
watch = "watch:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["pytest>=9.1.1"]
