[project]
name = "shirt"
version = "0.1.0"
description = "Paste a t-shirt image on top of the photo"
readme = "README.md"
authors = [{ name = "kuzminkdk", email = "kuzminkdk@gmail.com" }]
requires-python = ">=3.11"
dependencies = ["pillow>=12.3.0"]

[project.scripts]
shirt = "shirt:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
