[project]
name = "um"
version = "0.1.0"
description = "Counts “um” in the text"
readme = "README.md"
authors = [{ name = "kuzminkdk", email = "kuzminkdk@gmail.com" }]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
um = "um:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["pytest>=9.1.1"]
