[project]
name = "degrees"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "kuzminklk", email = "kuzminkdk@gmail.com" }]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
degrees = "degrees:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["ruff>=0.16.8"]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
